### PR TITLE
Tf 10645/create contact form handler

### PR DESCRIPTION
**Pull request by emilyemilyemilyemilyemilyemily**
### Ticket(s)

https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recDYN1fAgGDmJB3z

### Type of change

- [ x] New feature (non-breaking change which adds functionality)

### Description

Context: 
https://docs.google.com/document/d/1I3e1gh2HEkHALvTbVPWSjWb840FfuYyAmnL2jwnSuqY/edit#heading=h.npashoj11pcrhttps://docs.google.com/document/d/1P9_lk50jeYj8seUsxci9lhxhCKJ5iNlFMgt7bAhvF3s/edit#heading=h.nk3qsjen004f

### Review your work

- [x ] Everything works as expected
- [ x] Check for any uncaught ESLint problems

#### Code Clarity and Readability
- [ x] Are variable and function names descriptive, meaningful, in the appropriate case (ex: snake, camel)?
- [ x] Is the code self-explanatory and easy to understand?
- [x ] Are comments used where necessary to explain complex logic or provide additional context?

#### Code Efficiency
- [x ] Is the code DRY?
- [x ] Are there any areas of unnecessary complexity or duplication that might benefit from refactoring?

#### Code Modularity and Reusability
- [ x] Is the code and any new components organized in a logical location in the directory?
- [x ] Can any code snippets be refactored into reusable components?

#### Best Practices and Coding Standards
- [x ] Does the code follow the established coding standards and style guide of the project?
- [x ] Are there any violations of best practices that should be addressed?

### Overall PR Checklist:

- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation (if applicable)
- [x ] There are no new linting errors/problems in my code
- [x ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x ] I have filled this PR out fully, and cleaned up any extraneous items so that it is clear and easy to understand

### CODE REVIEW

**Comment by e-papanicolas** [comment]
@emilyemilyemilyemilyemilyemily this looks great, should we hold on the addition of the in-review submission architecture doc?

**Review by e-papanicolas — APPROVED** [review]

**Comment by emilyemilyemilyemilyemilyemily** [comment]
@e-papanicolas sure!

**Comment by emilyemilyemilyemilyemilyemily** [comment]
testing

**Comment by emilyemilyemilyemilyemilyemily** [comment]
Build failed. Logs:
```
2024-02-09T22:28:34.957Z [INFO]: # Cloning repository: git@github.com:clearviction-devs/clearviction-wa.git
2024-02-09T22:28:36.973Z [INFO]: 
2024-02-09T22:28:36.974Z [INFO]: Cloning into 'clearviction-wa'...
2024-02-09T22:28:37.303Z [INFO]: From https://github.com/clearviction-devs/clearviction-wa
                                 * [new ref]         refs/pull/171/head -> pr-171
                                 Switched to branch 'pr-171'
2024-02-09T22:28:37.523Z [INFO]: Successfully cleaned up Git credentials
2024-02-09T22:28:37.524Z [INFO]: # Checking for Git submodules at: /codebuild/output/src487362801/src/clearviction-wa/.gitmodules
2024-02-09T22:28:37.532Z [INFO]: # Retrieving environment cache...
2024-02-09T22:28:37.572Z [WARNING]: ! Unable to write cache: {"code":"ERR_BAD_REQUEST","message":"Request failed with status code 404"})}
2024-02-09T22:28:37.572Z [INFO]: ---- Setting Up SSM Secrets ----
2024-02-09T22:28:37.572Z [INFO]: SSM params {"Path":"/amplify/dqqxalj4ndxdp/prbhb/","WithDecryption":true}
2024-02-09T22:28:37.611Z [WARNING]: !Failed to set up process.env.secrets
2024-02-09T22:28:41.538Z [INFO]: # Node version 18 is available for installation
2024-02-09T22:28:41.652Z [INFO]: # Installing Node version 18
2024-02-09T22:29:43.721Z [INFO]: # Now using Node version 18
2024-02-09T22:29:43.841Z [INFO]: # Retrieving cache...
2024-02-09T22:29:43.883Z [INFO]: # Retrieved cache
2024-02-09T22:29:48.915Z [INFO]: ## Starting Backend Build
                                 ## Checking for associated backend environment...
                                 ## No backend environment association found, continuing...
                                 ## Completed Backend Build
2024-02-09T22:29:48.923Z [INFO]: {"backendDuration": 0}
                                 ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2024-02-09T22:30:26.316Z [INFO]: > open-seattle-nextjstailwind-demo@0.1.0 prepare
                                 > husky install
2024-02-09T22:30:26.368Z [INFO]: husky - Git hooks installed
2024-02-09T22:30:26.386Z [INFO]: added 976 packages, and audited 977 packages in 37s
2024-02-09T22:30:26.387Z [INFO]: 176 packages are looking for funding
                                 run `npm fund` for details
2024-02-09T22:30:26.388Z [INFO]: found 0 vulnerabilities
2024-02-09T22:30:26.422Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: npm run build
2024-02-09T22:30:26.703Z [INFO]: > open-seattle-nextjstailwind-demo@0.1.0 build
                                 > export build=true && next build
2024-02-09T22:30:27.253Z [INFO]: ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2024-02-09T22:30:27.258Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2024-02-09T22:30:27.259Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2024-02-09T22:30:27.342Z [INFO]: Linting and checking validity of types ...
2024-02-09T22:30:37.331Z [INFO]: Creating an optimized production build ...
2024-02-09T22:30:50.643Z [INFO]: ✓ Compiled successfully
2024-02-09T22:30:50.652Z [INFO]: Collecting page data ...
2024-02-09T22:30:53.449Z [INFO]: Generating static pages (0/65) ...
2024-02-09T22:30:55.507Z [INFO]: Generating static pages (16/65)
2024-02-09T22:30:57.538Z [INFO]: Generating static pages (32/65)
2024-02-09T22:30:59.786Z [INFO]: Generating static pages (48/65)
2024-02-09T22:31:01.255Z [INFO]: ✓ Generating static pages (65/65)
2024-02-09T22:31:17.361Z [INFO]: Finalizing page optimization ...
2024-02-09T22:31:17.366Z [INFO]: Collecting build traces ...
2024-02-09T22:31:20.562Z [INFO]: 
2024-02-09T22:31:20.568Z [INFO]: Route (pages)                                        Size     First Load JS
                                 ┌ ○ /                                                9.56 kB         208 kB
                                 ├   /_app                                            0 B             143 kB
                                 ├ ○ /404                                             182 B           143 kB
                                 ├ ○ /about                                           3.08 kB         186 kB
                                 ├ λ /api/revalidate                                  0 B             143 kB
                                 ├ ● /calculator/[slug] (13552 ms)                    186 kB          366 kB
                                 ├   ├ /calculator/m-circ-main-4-ineligible (598 ms)
                                 ├   ├ /calculator/m-offense-dv-1-cont (553 ms)
                                 ├   ├ /calculator/m-offense-pro-5-ineligible
                                 ├   ├ /calculator/m-offense-pro-6-eligible
                                 ├   ├ /calculator/m-terms-main-3-ineligible
                                 ├   ├ /calculator/m-offense-pro-7-cont
                                 ├   ├ /calculator/m-offense-pro-1-cont
                                 ├   └ [+49 more paths]
                                 ├ ○ /contact                                         4.22 kB         163 kB
                                 ├ ○ /donate                                          4.39 kB         186 kB
                                 ├ ○ /get-involved (343 ms)                           25.5 kB         228 kB
                                 ├   └ css/4df78f2cd73d6b26.css                       1.13 kB
                                 ├ ○ /get-started                                     5.34 kB         192 kB
                                 └ ○ /why-vacate                                      6.3 kB          188 kB
                                 + First Load JS shared by all                        143 kB
                                 ├ chunks/framework-467b11a89995b152.js             45.4 kB
                                 ├ chunks/main-75bdb96a41ba80f4.js                  33.1 kB
                                 ├ chunks/pages/_app-1a36736ad88442b0.js            62.1 kB
                                 ├ chunks/webpack-6cc2ac675212e550.js               2.09 kB
                                 └ css/c6b4809f3cddaab8.css                         831 B
                                 λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
2024-02-09T22:31:20.617Z [INFO]: # Completed phase: build
                                 ## Completed Frontend Build
2024-02-09T22:31:20.688Z [INFO]: ## Build completed successfully
2024-02-09T22:31:20.689Z [INFO]: # Starting caching...
2024-02-09T22:31:20.698Z [INFO]: # Creating cache artifact...
2024-02-09T22:31:41.130Z [INFO]: # Created cache artifact
2024-02-09T22:31:41.311Z [INFO]: # Uploading cache artifact...
2024-02-09T22:31:48.131Z [INFO]: # Uploaded cache artifact
2024-02-09T22:31:48.215Z [INFO]: # Caching completed
2024-02-09T22:32:14.757Z [INFO]: # Starting environment caching...
2024-02-09T22:32:14.889Z [INFO]: # Environment caching completed
Terminating logging...
\```

**Comment by emilyemilyemilyemilyemilyemily** [comment]
Build failed. Logs:
2024-02-09T22:28:34.957Z [INFO]: # Cloning repository: git@github.com:clearviction-devs/clearviction-wa.git
2024-02-09T22:28:36.973Z [INFO]: 
2024-02-09T22:28:36.974Z [INFO]: Cloning into 'clearviction-wa'...
2024-02-09T22:28:37.303Z [INFO]: From https://github.com/clearviction-devs/clearviction-wa
                                 * [new ref]         refs/pull/171/head -> pr-171
                                 Switched to branch 'pr-171'
2024-02-09T22:28:37.523Z [INFO]: Successfully cleaned up Git credentials
2024-02-09T22:28:37.524Z [INFO]: # Checking for Git submodules at: /codebuild/output/src487362801/src/clearviction-wa/.gitmodules
2024-02-09T22:28:37.532Z [INFO]: # Retrieving environment cache...
2024-02-09T22:28:37.572Z [WARNING]: ! Unable to write cache: {"code":"ERR_BAD_REQUEST","message":"Request failed with status code 404"})}
2024-02-09T22:28:37.572Z [INFO]: ---- Setting Up SSM Secrets ----
2024-02-09T22:28:37.572Z [INFO]: SSM params {"Path":"/amplify/dqqxalj4ndxdp/prbhb/","WithDecryption":true}
2024-02-09T22:28:37.611Z [WARNING]: !Failed to set up process.env.secrets
2024-02-09T22:28:41.538Z [INFO]: # Node version 18 is available for installation
2024-02-09T22:28:41.652Z [INFO]: # Installing Node version 18
2024-02-09T22:29:43.721Z [INFO]: # Now using Node version 18
2024-02-09T22:29:43.841Z [INFO]: # Retrieving cache...
2024-02-09T22:29:43.883Z [INFO]: # Retrieved cache
2024-02-09T22:29:48.915Z [INFO]: ## Starting Backend Build
                                 ## Checking for associated backend environment...
                                 ## No backend environment association found, continuing...
                                 ## Completed Backend Build
2024-02-09T22:29:48.923Z [INFO]: {"backendDuration": 0}
                                 ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2024-02-09T22:30:26.316Z [INFO]: > open-seattle-nextjstailwind-demo@0.1.0 prepare
                                 > husky install
2024-02-09T22:30:26.368Z [INFO]: husky - Git hooks installed
2024-02-09T22:30:26.386Z [INFO]: added 976 packages, and audited 977 packages in 37s
2024-02-09T22:30:26.387Z [INFO]: 176 packages are looking for funding
                                 run `npm fund` for details
2024-02-09T22:30:26.388Z [INFO]: found 0 vulnerabilities
2024-02-09T22:30:26.422Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: npm run build
2024-02-09T22:30:26.703Z [INFO]: > open-seattle-nextjstailwind-demo@0.1.0 build
                                 > export build=true && next build
2024-02-09T22:30:27.253Z [INFO]: ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2024-02-09T22:30:27.258Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2024-02-09T22:30:27.259Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2024-02-09T22:30:27.342Z [INFO]: Linting and checking validity of types ...
2024-02-09T22:30:37.331Z [INFO]: Creating an optimized production build ...
2024-02-09T22:30:50.643Z [INFO]: ✓ Compiled successfully
2024-02-09T22:30:50.652Z [INFO]: Collecting page data ...
2024-02-09T22:30:53.449Z [INFO]: Generating static pages (0/65) ...
2024-02-09T22:30:55.507Z [INFO]: Generating static pages (16/65)
2024-02-09T22:30:57.538Z [INFO]: Generating static pages (32/65)
2024-02-09T22:30:59.786Z [INFO]: Generating static pages (48/65)
2024-02-09T22:31:01.255Z [INFO]: ✓ Generating static pages (65/65)
2024-02-09T22:31:17.361Z [INFO]: Finalizing page optimization ...
2024-02-09T22:31:17.366Z [INFO]: Collecting build traces ...
2024-02-09T22:31:20.562Z [INFO]: 
2024-02-09T22:31:20.568Z [INFO]: Route (pages)                                        Size     First Load JS
                                 ┌ ○ /                                                9.56 kB         208 kB
                                 ├   /_app                                            0 B             143 kB
                                 ├ ○ /404                                             182 B           143 kB
                                 ├ ○ /about                                           3.08 kB         186 kB
                                 ├ λ /api/revalidate                                  0 B             143 kB
                                 ├ ● /calculator/[slug] (13552 ms)                    186 kB          366 kB
                                 ├   ├ /calculator/m-circ-main-4-ineligible (598 ms)
                                 ├   ├ /calculator/m-offense-dv-1-cont (553 ms)
                                 ├   ├ /calculator/m-offense-pro-5-ineligible
                                 ├   ├ /calculator/m-offense-pro-6-eligible
                                 ├   ├ /calculator/m-terms-main-3-ineligible
                                 ├   ├ /calculator/m-offense-pro-7-cont
                                 ├   ├ /calculator/m-offense-pro-1-cont
                                 ├   └ [+49 more paths]
                                 ├ ○ /contact                                         4.22 kB         163 kB
                                 ├ ○ /donate                                          4.39 kB         186 kB
                                 ├ ○ /get-involved (343 ms)                           25.5 kB         228 kB
                                 ├   └ css/4df78f2cd73d6b26.css                       1.13 kB
                                 ├ ○ /get-started                                     5.34 kB         192 kB
                                 └ ○ /why-vacate                                      6.3 kB          188 kB
                                 + First Load JS shared by all                        143 kB
                                 ├ chunks/framework-467b11a89995b152.js             45.4 kB
                                 ├ chunks/main-75bdb96a41ba80f4.js                  33.1 kB
                                 ├ chunks/pages/_app-1a36736ad88442b0.js            62.1 kB
                                 ├ chunks/webpack-6cc2ac675212e550.js               2.09 kB
                                 └ css/c6b4809f3cddaab8.css                         831 B
                                 λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
2024-02-09T22:31:20.617Z [INFO]: # Completed phase: build
                                 ## Completed Frontend Build
2024-02-09T22:31:20.688Z [INFO]: ## Build completed successfully
2024-02-09T22:31:20.689Z [INFO]: # Starting caching...
2024-02-09T22:31:20.698Z [INFO]: # Creating cache artifact...
2024-02-09T22:31:41.130Z [INFO]: # Created cache artifact
2024-02-09T22:31:41.311Z [INFO]: # Uploading cache artifact...
2024-02-09T22:31:48.131Z [INFO]: # Uploaded cache artifact
2024-02-09T22:31:48.215Z [INFO]: # Caching completed
2024-02-09T22:32:14.757Z [INFO]: # Starting environment caching...
2024-02-09T22:32:14.889Z [INFO]: # Environment caching completed
Terminating logging...

**Review by e-papanicolas — APPROVED** [review]

**Pull request merged**
