### PR TITLE
ci: workflow for testing pull request

### PR DESCRIPTION
**Pull request by LeoFuna**
### Ticket(s)

- _[12066](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec4vBjACIIMykPDT)_

### Type of change
- [x] Documentation or testing

### Description

We need to guarantee that all PRs created are passing on ours tests.
Because of that, this PR creates a workflow to run our tests on every PR created against `staging` branch.

image

#### Preview
Use your local build.

- [x] Everything works as expected
- [ ] Check changed page(s)
- [ ] Click through calculator if changes were made
- [ ] Compare figma screenshot with the changes
- [ ] Compare linked Figma section to changes made
- [ ] Refresh the page, check that using the go-back button works as expected
- [ ] Check large screen size (>1400)
- [ ] Check tablet screen size (<786)
- [ ] Check mobile screen size (<375)
- [ ] Check that links work
- [x] Check the console for errors or warnings
- [x] Check the terminal for any errors or problems
- [x] Check for any uncaught ESLint problems

#### Code Clarity and Readability
- [x] Are variable and function names descriptive, meaningful, in the appropriate case (ex: snake, camel)?
- [x] Is the code self-explanatory and easy to understand?
- [x] Are comments used where necessary to explain complex logic or provide additional context?

#### Code Efficiency
- [x] Is the code DRY?
- [x] Are there any areas of unnecessary complexity or duplication that might benefit from refactoring?

#### Code Modularity and Reusability
- [ ] Is the code and any new components organized in a logical location in the directory?
- [ ] Can any code snippets be refactored into reusable components?
- [ ] Are there opportunities to abstract common functionality into separate functions or classes?
- [ ] Is there good use of CSS selectors when creating new components or refactoring old ones?

#### Best Practices and Coding Standards
- [ ] Does the code follow the established coding standards and style guide of the project?
- [ ] Are there any violations of best practices that should be addressed?
- [ ] Are there any hard-coded strings or UI elements that should be externalized?
- [ ] Are all measurement units in REM? (border-radius, borders should still be in px)
- [ ] Is there any unnecessary commented out code lingering?
- [ ] Are all files TypeScript?

### Overall PR Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings in the console
- [x] There are no new linting errors/problems in my code
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] I have filled out the new 3rd party dependency checklist (if applicable)
- [x] I have filled this PR out fully, and cleaned up any extraneous items so that it is clear and easy to understand

### CODE REVIEW

**Review by sramalho94 — CHANGES_REQUESTED** [review]
hey @LeoFuna,
This is great! I can't wait to further expand the cypress test to fully navigate the calculator user flow. One quick note, I noticed this in the workflow console logs for the `cypress run` step on lns 14-18:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sanity/webhook@4.0.2',
npm WARN EBADENGINE   required: { node: '>=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
npm WARN EBADENGINE }
```

Should we set the node-version to 20 on lns 17 & 36 in `.github/workflows/pr-testing.yml` to fix this?

**Comment by e-papanicolas** [comment]
> hey @LeoFuna,
> 
> This is great! I can't wait to further expand the cypress test to fully navigate the calculator user flow. One quick note, I noticed this in the workflow console logs for the `cypress run` step on lns 14-18:
> 
> 
> 
> ```
> 
> npm WARN EBADENGINE Unsupported engine {
> 
> npm WARN EBADENGINE   package: '@sanity/webhook@4.0.2',
> 
> npm WARN EBADENGINE   required: { node: '>=20.0.0' },
> 
> npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
> 
> npm WARN EBADENGINE }
> 
> ```
> 
> 
> 
> Should we set the node-version to 20 on lns 17 & 36 in `.github/workflows/pr-testing.yml` to fix this?
> 
> 

@sramalho94 i wonder if we need to update the node version in amplify?

**Comment by LeoFuna** [comment]
> hey @LeoFuna, This is great! I can't wait to further expand the cypress test to fully navigate the calculator user flow. One quick note, I noticed this in the workflow console logs for the `cypress run` step on lns 14-18:
> 
> ```
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: '@sanity/webhook@4.0.2',
> npm WARN EBADENGINE   required: { node: '>=20.0.0' },
> npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
> npm WARN EBADENGINE }
> ```
> 
> Should we set the node-version to 20 on lns 17 & 36 in `.github/workflows/pr-testing.yml` to fix this?

Hi @sramalho94 and @e-papanicolas thx for reviewing this PR.

Thats a good point! I can check if we can use node 20 in our workflow to fix this.

But as Eleni said, im not sure if its good to have a test with an enviroment node version diff from our application node version. Maybe if I can use node 20, would be good to change all our node versions to 20 too.

**Comment by sramalho94** [comment]
> > hey @LeoFuna, This is great! I can't wait to further expand the cypress test to fully navigate the calculator user flow. One quick note, I noticed this in the workflow console logs for the `cypress run` step on lns 14-18:
> > ```
> > npm WARN EBADENGINE Unsupported engine {
> > npm WARN EBADENGINE   package: '@sanity/webhook@4.0.2',
> > npm WARN EBADENGINE   required: { node: '>=20.0.0' },
> > npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
> > npm WARN EBADENGINE }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should we set the node-version to 20 on lns 17 & 36 in `.github/workflows/pr-testing.yml` to fix this?
> 
> Hi @sramalho94 and @e-papanicolas thx for reviewing this PR.
> 
> Thats a good point! I can check if we can use node 20 in our workflow to fix this.
> 
> But as Eleni said, im not sure if its good to have a test with an enviroment node version diff from our application node version. Maybe if I can use node 20, would be good to change all our node versions to 20 too.

hey @LeoFuna, I agree that we should update the node version of prod and staging to 20. If you want to do a little testing to see if everything works with node 20 that would be awesome. If not we can plan to upgrade as part of the package update TG, what do you think @e-papanicolas ?

**Comment by LeoFuna** [comment]
@sramalho94 I tested about using node 20 and everything seems to be ok to use it!
I believe we can do this upgrade :tada:

**Comment by e-papanicolas** [comment]
> PR has dependency issues:
> 
> # npm audit report
> follow-redirects <=1.15.5 Severity: moderate follow-redirects' Proxy-Authorization header kept across hosts - [GHSA-cxjh-pqwp-8mfp](https://github.com/advisories/GHSA-cxjh-pqwp-8mfp) fix available via `npm audit fix` node_modules/follow-redirects
> 
> 1 moderate severity vulnerability
> 
> To address all issues, run: npm audit fix

@sramalho94 I am wondering if this workflow is redundant now with dependabot having also created a pull request for this, thoughts on removing it?

**Comment by sramalho94** [comment]
> > PR has dependency issues:
> > # npm audit report
> > follow-redirects <=1.15.5 Severity: moderate follow-redirects' Proxy-Authorization header kept across hosts - [GHSA-cxjh-pqwp-8mfp](https://github.com/advisories/GHSA-cxjh-pqwp-8mfp) fix available via `npm audit fix` node_modules/follow-redirects
> > 1 moderate severity vulnerability
> > To address all issues, run: npm audit fix
> 
> @sramalho94 I am wondering if this workflow is redundant now with dependabot having also created a pull request for this, thoughts on removing it?

@e-papanicolas  I think that's a good idea! Do you think there are any edge cases that dependabot might miss, that the workflow would catch? If not I think we should remove the workflow.

**Review by sramalho94 — APPROVED** [review]

**Pull request merged**
